export const images = {
    lisichka: require('../assets/images/lisichka.png'),
    lozhnyZontik: require('../assets/images/lozhnyZontik.png'),
    mukhomor: require('../assets/images/mukhomor.png'),
    openok: require('../assets/images/openok.png'),
    blednayaPoganka: require('../assets/images/blednayaPoganka.png'),
    belayaPoganka: require('../assets/images/belayaPoganka.png'),
    syroezhka: require('../assets/images/syroezhka.png'),
    ryzhik: require('../assets/images/ryzhik.png'),
    zelenushka: require('../assets/images/zelenushka.png'),
    grib: require('../assets/images/grib.svg'),
    belyi: require('../assets/images/belyi.png'),    
    maslyenok: require('../assets/images/maslyenok.png'),
    syroezhka: require('../assets/images/syroezhka.png'), 
    champignons: require('../assets/images/champignons.png'),
    goluboyGruzd: require('../assets/images/goluboyGruzd.png'),
    shiitake: require('../assets/images/shiitake.png'),
    smorchok: require('../assets/images/smorchok.png'),
    truffle: require('../assets/images/truffle.png'),
    veshenka: require('../assets/images/veshenka.png'),
    muchnistyiMukhomor: require('../assets/images/muchnistyiMukhomor.png'),
};
